### PR TITLE
CNF-11459: update script to install go version using the new telco-runner image.

### PR DESCRIPTION
**Pull request by nishant-parekh**

### CODE REVIEW

**Comment by nishant-parekh** [comment]
@jzding for some reason the other PR was not updating with latest changes. I have addressed your comments from the older [PR](https://github.com/openshift/ptp-operator/pull/451) here PTAL when you get a chance:

**Review by jzding — APPROVED** [review]
/lgtm

**Review by jzding — APPROVED** [review]
/lgtm

**Pull request merged**
