### PR TITLE
Bug 1830496: Remove runlevel from the operator's namespace and use SCC

### PR DESCRIPTION
**Pull request by fedepaol**
Use the privileged scc for the ptp-daemon.

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@fedepaol please also add role.yaml and rolebinding.yaml in `hack/undeploy.sh`

**Comment by fedepaol** [comment]
> @fedepaol please also add role.yaml and rolebinding.yaml in `hack/undeploy.sh`

Ah right, I missed that.

**Pull request merged**
