### PR TITLE
Bug OCPBUGS-22653: fix SNO lease duration

### PR DESCRIPTION
**Pull request by jzding**
leaseDurationSeconds should be 270 seconds for SNO instead of default 15 seconds.

Add back namespace to be consistent with previous releases.

### CODE REVIEW

**Comment by aneeshkp** [comment]
please add ci to verify  the lease object

**Comment by aneeshkp** [comment]
add lease object if exist validating the duration 
https://github.com/openshift/ptp-operator/blob/master/test/validation/tests/validation.go#L58

**Comment by jzding** [comment]
> add lease object if exist validating the duration https://github.com/openshift/ptp-operator/blob/master/test/validation/tests/validation.go#L58

unit test added

**Review by aneeshkp — APPROVED** [review]

**Pull request merged**
