### PR TITLE
Create policy in tests

### PR DESCRIPTION
**Pull request by SchSeba**
Base on https://github.com/openshift/ptp-operator/pull/44

Run the tests on any cluster

This commit allow running the functional tests without any special configuration in the cluster.
The only requirement is the operator to be installed
    
Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Comment by zshi-redhat** [comment]
@SchSeba both PRs (#44 & #45) are updating vendor dependencies, does it require order to apply?

**Comment by SchSeba** [comment]
@zshi-redhat This PR is base on #44 let me rebase it

**Comment by SchSeba** [comment]
@zshi-redhat @fedepaol Can you take a look now?

This PR only contains the test change now :)

**Comment by zshi-redhat** [comment]
> @zshi-redhat @fedepaol Can you take a look now?
> 
> This PR only contains the test change now :)

One of the tests (`Slave can sync to master`) failed in my testing, looks like the expected string of being a grandmaster clock can be changed:

The test assumes it would be `assuming the grand master role`
Blow test output shows it's `selecting CLOCK_REALTIME as the master clock`

```
          I0407 11:11:52.314602  192953 daemon.go:113] updating NodePTPProfile to:
          I0407 11:11:52.314612  192953 daemon.go:114] ------------------------------------
          I0407 11:11:52.314622  192953 daemon.go:104] Profile Name: grandmaster
          I0407 11:11:52.314632  192953 daemon.go:104] Interface: ens785f0
          I0407 11:11:52.314643  192953 daemon.go:104] Ptp4lOpts:  -m --summary_interval 1
          I0407 11:11:52.314653  192953 daemon.go:104] Phc2sysOpts: -a -r -r -m -u 1
          I0407 11:11:52.314663  192953 daemon.go:120] ------------------------------------
          I0407 11:11:53.314915  192953 daemon.go:190] Starting phc2sys...
          I0407 11:11:53.314973  192953 daemon.go:191] phc2sys cmd: &{Path:/usr/sbin/phc2sys Args:[/usr/sbin/phc2sys -a -r -r -m -u 1] Env:[] Dir: Stdin:<nil> Stdout:<nil> Stderr:<nil> ExtraFiles:[] SysProcAttr:<nil> Process:<nil> ProcessState:<nil> ctx:<nil> lookPathErr:<nil> finished:false childFiles:[] closeAfterStart:[] closeAfterWait:[] goroutine:[] errch:<nil> waitDone:<nil>}
          I0407 11:11:54.315132  192953 daemon.go:190] Starting ptp4l...
          I0407 11:11:54.315177  192953 daemon.go:191] ptp4l cmd: &{Path:/usr/sbin/ptp4l Args:[/usr/sbin/ptp4l -f /etc/ptp4l.conf -i ens785f0  -m --summary_interval 1] Env:[] Dir: Stdin:<nil> Stdout:<nil> Stderr:<nil> ExtraFiles:[] SysProcAttr:<nil> Process:<nil> ProcessState:<nil> ctx:<nil> lookPathErr:<nil> finished:false childFiles:[] closeAfterStart:[] closeAfterWait:[] goroutine:[] errch:<nil> waitDone:<nil>}
          ptp4l[5177.575]: selected /dev/ptp0 as PTP clock
          phc2sys[5177.577]: Waiting for ptp4l...
          ptp4l[5177.577]: driver rejected most general HWTSTAMP filter
          ptp4l[5177.577]: port 1: INITIALIZING to FAULTY on FAULT_DETECTED (FT_UNSPECIFIED)
          ptp4l[5177.577]: port 0: INITIALIZING to LISTENING on INIT_COMPLETE
          phc2sys[5178.578]: Waiting for ptp4l...
          phc2sys[5179.579]: reconfiguring after port state change
          phc2sys[5179.579]: selecting ens785f0 for synchronization
          phc2sys[5179.579]: selecting CLOCK_REALTIME as the master clock
          phc2sys[5179.579]: ens785f0 rms 36592943448 max 36592943448 freq     +0 +/-   0 delay   640 +/-   0
          phc2sys[5180.580]: ens785f0 rms 36592864800 max 36592864800 freq +78631 +/-   0 delay   646 +/-   0
          phc2sys[5181.580]: ens785f0 rms 1490 max 1490 freq +77141 +/-   0 delay   579 +/-   0
          phc2sys[5182.580]: ens785f0 rms   15 max   15 freq +78169 +/-   0 delay   645 +/-   0
          phc2sys[5183.580]: ens785f0 rms  425 max  425 freq +78605 +/-   0 delay   575 +/-   0
          phc2sys[5184.581]: ens785f0 rms  461 max  461 freq +78768 +/-   0 delay   643 +/-   0

```

**Comment by SchSeba** [comment]
@zshi-redhat thanks I will take a look at the test because I didn't change it.

**Comment by SchSeba** [comment]
@zshi-redhat I checked it on my environment the logs we are searching is for the ptp4l
```
ptp4l[116.983]: assuming the grand master role
```

Can be that it was printed later did you env is still running and you can take a look?
If that is the case I can add a retry on the log fetch.

**Comment by zshi-redhat** [comment]
> > @zshi-redhat @fedepaol Can you take a look now?
> > This PR only contains the test change now :)
> 
> One of the tests (`Slave can sync to master`) failed in my testing, looks like the expected string of being a grandmaster clock can be another value:
> 
> The test assumes it would be `assuming the grand master role`
> Blow test output shows it's `selecting CLOCK_REALTIME as the master clock`
> 

Given it's passing in @SchSeba environment , we believe this is device specific issue for a NIC that claims to support PTP but actually not be able to function corretly. it should not block the PR from merging.

/lgtm

**Pull request merged**
