### PR TITLE
Bug 1828692: Provide support for running tests in a disconnected cluster.

### PR DESCRIPTION
**Pull request by fedepaol**

### CODE REVIEW

**Comment by fedepaol** [comment]
/hold
Let's see if we get official images on quay

**Comment by SchSeba** [comment]
I think we need to remove this 

https://github.com/openshift/ptp-operator/blob/92f3d20c48f9b8e75e78bc2579c01937c44ef830/test/utils/pods/pods.go#L22

and also check if we use this image 
https://github.com/openshift/ptp-operator/blob/92f3d20c48f9b8e75e78bc2579c01937c44ef830/test/utils/pods/pods.go#L37

**Comment by fedepaol** [comment]
> hugePageCommand

Removed both

**Comment by fedepaol** [comment]
The image is not even used, we will clean up the test utils later.

**Pull request closed without merging**
