### PR TITLE
[release 4.9] Bug 2055272:change ImagePullPolicy 

### PR DESCRIPTION
**Pull request by aneeshkp**
Change the pull policy for all the images to be IfNotPresent
Signed-off-by: Aneesh Puttur [aneeshputtur@gmail.com]

### CODE REVIEW

**Review by cgoncalves — CHANGES_REQUESTED** [review]
The imagePullPolicy for cloud-event-proxy was dropped in the backport process.

**Comment by aneeshkp** [comment]
@cgoncalves added imagePolicy for cloud-event-proxy
/review @SchSeba

**Comment by aneeshkp** [comment]
@kedark3 , @zhaozhanqi , can you add a cherry-pick-approved label pls.

**Pull request merged**
