### PR TITLE
[release-4.12]  OCPBUGS-20185: ptp4l process restarted unexpected with dual NIC boundary clocks configured

### PR DESCRIPTION
**Pull request by aneeshkp**
fix restart of process due to non deterministic order of profile name on  each reconcile

### CODE REVIEW

**Comment by aneeshkp** [comment]
/retitle [release-4.12]  OCPBUGS-20185: ptp4l process restarted unexpected with dual NIC boundary clocks configured

**Review by jzding — APPROVED** [review]
/lgtm

**Pull request merged**
