### PR TITLE
Typo in README.md

### PR DESCRIPTION
**Pull request by dbaker-rh**
Simple typo fix

### CODE REVIEW

**Comment by dbaker-rh** [comment]
Looks like a timeout --> "2020/09/10 16:21:46 pod didn't start running within 10 minutes:".

/test images

**Comment by zshi-redhat** [comment]
@dbaker-rh thanks for the fix!
we probably need to wait until master is open to 4.7 then merge this PR since any PR merging at this time requires a valid bugzilla associated with it. Alternative is to create a bugzilla and link it to this PR, then it will be merged.

**Pull request merged**
