### PR TITLE
Update README and CRD descriptions for http transport

### PR DESCRIPTION
**Pull request by jzding**
Update README and CRD descriptions for http transport.
No functional impact.

Signed-off-by: Jack Ding <jackding@gmail.com>

### CODE REVIEW

**Review by aneeshkp — APPROVED** [review]

**Comment by aneeshkp** [comment]
can you comment as update http transport details in readme and crds descriptions ?

**Comment by jzding** [comment]
> can you comment as update http transport details in readme and crds descriptions ?

done

**Review by aneeshkp — APPROVED** [review]

**Pull request merged**
