### PR TITLE
Bump the operator-sdk and the k8s api dependencies to version to 1.18.

### PR DESCRIPTION
**Pull request by fedepaol**

### CODE REVIEW

**Comment by fedepaol** [comment]
Validated:
```
• [SLOW TEST:12.042 seconds]
[ptp]
/root/fede/ptp-operator/test/ptp/ptp.go:32
  PTP e2e tests
  /root/fede/ptp-operator/test/ptp/ptp.go:88
    PTP metric is present
    /root/fede/ptp-operator/test/ptp/ptp.go:261
      on slave
      /root/fede/ptp-operator/test/ptp/ptp.go:277
------------------------------

JUnit report was created: /tmp/artifacts/unit_report.xml

Ran 9 of 9 Specs in 106.479 seconds
SUCCESS! -- 9 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```

**Comment by SchSeba** [comment]
/lgtm

@zshi-redhat anything from your side before we merge this PR?

**Comment by SchSeba** [comment]
/test e2e-aws
--

**Pull request merged**
