### PR TITLE
disable Plugin tests

### PR DESCRIPTION
**Pull request by nishant-parekh**
disabling test that is getting stuck

### CODE REVIEW

**Review by edcdavid — COMMENTED** [review]
I would also disable "It("Should check whether test plugin executes", func() {" since these test are related. Also run the test locally to make sure it passes this step

**Comment by josephdrichard** [comment]
Is there a bug open related to this?  What exactly is the issue?

**Comment by edcdavid** [comment]
> Is there a bug open related to this? What exactly is the issue?

not sure, seems to be crashing in CI.

**Review by edcdavid — APPROVED** [review]

**Pull request merged**
